// Animation timings are in seconds. Keep these restrained for readable motion.
// Colors, spacing, type, and breakpoints live at the top of src/styles.css.
export const motion = Object.freeze({
  ease: "power3.out",
  intro: 0.95,
  brandIntro: 0.65,
  menuOpen: 0.65,
  menuClose: 0.3,
  menuStagger: 0.055,
  preview: 0.4,
  disclosure: 0.42,
  panel: 0.35,
  reveal: 0.85,
  assembly: 1.1,
  layout: 0.4,
  press: 0.45,
  themeReveal: 1.05,
  themeRevealMobile: 0.88,
  themeFade: 0.36,
  signatureReturn: 0.8,
  svgTrace: 4,
  sculptureEntry: 0.9,
  sculptureScrollScreens: 0.75,
  sculptureSettle: 12,
  cardDepth: 55,
  cardTilt: 4,
  profileDepth: 36,
  profileTilt: 4,
  profileLift: 16,
  profileScrub: 0.25,
  profileFactDepth: 14,
  profileFactTilt: 0.8,
  profileFactLift: 1.5,
  sectionScrub: 0.6,
  principleDepth: 44,
  principleTilt: 4,
  principleLift: 24,
  principleStagger: 0.12,
  maxPixelRatio: 1.5,
});
